import { mkdirSync, writeFileSync } from 'fs';
import { dirname, resolve } from 'path';
import { fileURLToPath } from 'url';
import { Colors, generateCSSCustomProperties } from '../dist/colors.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const generateSCSSMixins = () => {
  // Generate SCSS mixins for theme colors
  const lightProps = generateCSSCustomProperties('light');
  const darkProps = generateCSSCustomProperties('dark');

  let scssContent = '/* Auto-generated SCSS mixins from TypeScript colors */\n';
  scssContent += '/* Do not edit this file directly - edit libs/constants/src/colors.ts instead */\n';
  scssContent += '/* Run: npm run generate:css to regenerate this file */\n\n';

  // Light theme mixin
  scssContent += '@mixin light-theme {\n';
  Object.entries(lightProps).forEach(([prop, value]) => {
    scssContent += `  ${prop}: ${value};\n`;
  });
  scssContent += '}\n\n';

  // Dark theme mixin
  scssContent += '@mixin dark-theme {\n';
  Object.entries(darkProps).forEach(([prop, value]) => {
    scssContent += `  ${prop}: ${value};\n`;
  });
  scssContent += '}\n';

  return scssContent;
};

// Generate SCSS mixins content
const scssContent = generateSCSSMixins();

// Define output path
const scssOutputPath = resolve(__dirname, '../dist/_theme-mixins.scss');

// Ensure directory exists
mkdirSync(dirname(scssOutputPath), { recursive: true });

// Write SCSS mixins file
writeFileSync(scssOutputPath, scssContent, 'utf8');
console.log(`✅ Generated SCSS theme mixins: ./dist/_theme-mixins.scss`);
console.log('📝 Use in SCSS files with: @use "@fennex-sand/constants/theme-mixins" as theme;');
console.log('📝 Then include mixins: @include theme.light-theme; or @include theme.dark-theme;');
