import { mkdirSync, writeFileSync } from 'fs';
import { dirname, resolve } from 'path';
import { fileURLToPath } from 'url';
import { Colors, generateCSSCustomProperties } from '../dist/colors.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const generateCSSFile = () => {
  // Generate CSS custom properties for both themes
  const lightProps = generateCSSCustomProperties('light');
  const darkProps = generateCSSCustomProperties('dark');

  // Generate CSS content
  let cssContent = '/* Auto-generated CSS custom properties from TypeScript colors */\n';
  cssContent += '/* Do not edit this file directly - edit libs/constants/src/colors.ts instead */\n';
  cssContent += '/* Run: npm run generate:css to regenerate this file */\n\n';

  // Light theme (default)
  cssContent += ':root {\n';
  Object.entries(lightProps).forEach(([prop, value]) => {
    cssContent += `  ${prop}: ${value};\n`;
  });
  cssContent += '}\n\n';

  // Dark theme using media query
  cssContent += '@media (prefers-color-scheme: dark) {\n';
  cssContent += '  :root {\n';
  Object.entries(darkProps).forEach(([prop, value]) => {
    cssContent += `    ${prop}: ${value};\n`;
  });
  cssContent += '  }\n';
  cssContent += '}\n\n';

  // Alternative: CSS class-based dark mode
  cssContent += '/* Alternative: class-based dark mode */\n';
  cssContent += '.dark {\n';
  Object.entries(darkProps).forEach(([prop, value]) => {
    cssContent += `  ${prop}: ${value};\n`;
  });
  cssContent += '}\n\n';

  // Add data attribute selector for dark mode
  cssContent += '/* Data attribute dark mode */\n';
  cssContent += '[data-theme="dark"] {\n';
  Object.entries(darkProps).forEach(([prop, value]) => {
    cssContent += `  ${prop}: ${value};\n`;
  });
  cssContent += '}\n';

  return cssContent;
};

// Generate CSS content
const cssContent = generateCSSFile();

// Define output path - generate CSS in the constants package
const outputPath = resolve(__dirname, '../dist/colors.css');

// Ensure directory exists
mkdirSync(dirname(outputPath), { recursive: true });

// Write CSS file
writeFileSync(outputPath, cssContent, 'utf8');

console.log(`✅ Generated CSS colors file: ./dist/colors.css`);
console.log('📝 Import in your apps with: import "@fennex-sand/constants/colors.css"');
