import { mkdirSync, writeFileSync } from 'fs';
import { dirname, resolve } from 'path';
import { fileURLToPath } from 'url';
import { Colors, generateCSSCustomProperties } from '../dist/colors.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const generateCSSFile = () => {
  // Generate CSS custom properties for both themes
  const lightProps = generateCSSCustomProperties('light');
  const darkProps = generateCSSCustomProperties('dark');

  // Generate CSS content
  let cssContent = '/* Auto-generated CSS custom properties from TypeScript colors */\n';
  cssContent += '/* Do not edit this file directly - edit libs/constants/src/colors.ts instead */\n';
  cssContent += '/* Run: npm run generate:css to regenerate this file */\n\n';

  // Light theme (default)
  cssContent += ':root {\n';
  Object.entries(lightProps).forEach(([prop, value]) => {
    cssContent += `  ${prop}: ${value};\n`;
  });
  cssContent += '}\n\n';

  // Dark theme using media query
  cssContent += '@media (prefers-color-scheme: dark) {\n';
  cssContent += '  :root {\n';
  Object.entries(darkProps).forEach(([prop, value]) => {
    cssContent += `    ${prop}: ${value};\n`;
  });
  cssContent += '  }\n';
  cssContent += '}\n\n';

  // Alternative: CSS class-based dark mode
  cssContent += '/* Alternative: class-based dark mode */\n';
  cssContent += '.dark {\n';
  Object.entries(darkProps).forEach(([prop, value]) => {
    cssContent += `  ${prop}: ${value};\n`;
  });
  cssContent += '}\n\n';

  // Add data attribute selector for dark mode
  cssContent += '/* Data attribute dark mode */\n';
  cssContent += '[data-theme="dark"] {\n';
  Object.entries(darkProps).forEach(([prop, value]) => {
    cssContent += `  ${prop}: ${value};\n`;
  });
  cssContent += '}\n';

  return cssContent;
};

const generateSCSSMixins = () => {
  // Generate SCSS mixins for theme colors
  const lightProps = generateCSSCustomProperties('light');
  const darkProps = generateCSSCustomProperties('dark');

  let scssContent = '/* Auto-generated SCSS mixins from TypeScript colors */\n';
  scssContent += '/* Do not edit this file directly - edit libs/constants/src/colors.ts instead */\n';
  scssContent += '/* Run: npm run generate:css to regenerate this file */\n\n';

  // Light theme mixin
  scssContent += '@mixin light-theme {\n';
  Object.entries(lightProps).forEach(([prop, value]) => {
    scssContent += `  ${prop}: ${value};\n`;
  });
  scssContent += '}\n\n';

  // Dark theme mixin
  scssContent += '@mixin dark-theme {\n';
  Object.entries(darkProps).forEach(([prop, value]) => {
    scssContent += `  ${prop}: ${value};\n`;
  });
  scssContent += '}\n';

  return scssContent;
};

// Generate CSS content
const cssContent = generateCSSFile();
const scssContent = generateSCSSMixins();

// Define output paths
const cssOutputPath = resolve(__dirname, '../dist/colors.css');
const scssOutputPath = resolve(__dirname, '../dist/_theme-mixins.scss');

// Ensure directory exists
mkdirSync(dirname(cssOutputPath), { recursive: true });

// Write CSS file
writeFileSync(cssOutputPath, cssContent, 'utf8');
console.log(`✅ Generated CSS colors file: ./dist/colors.css`);
console.log('📝 Import in your apps with: import "@fennex-sand/constants/colors.css"');

// Write SCSS mixins file
writeFileSync(scssOutputPath, scssContent, 'utf8');
console.log(`✅ Generated SCSS mixins file: ./dist/_theme-mixins.scss`);
console.log('📝 Use in SCSS files with: @use "@fennex-sand/constants/theme-mixins" as theme;');
